3ein39/BookEra

app.js, controllers/bookController.js, controllers/orderController.js, controllers/orderDetailController.js, controllers/userController.js, routes/books.js, routes/orders.js, routes/orders_detail.js, routes/users.js
- Added routes and controller for orders. This includes routes for creating, reading, updating, and deleting orders.
- Added a new route and controller for order details. This allows us to handle operations related to order details such as creating, reading, updating, and deleting order details.
- Added user routes and controller functions. These new additions will handle user-related operations.
Please review the changes and merge the pull request if everything is in order. If there are any issues or questions, feel free to leave comments.
=> Add some routes and thier controller functions

app.js, controllers/userController.js, routes/users.js, views/login_form.ejs, views/signup_form.ejs
- Added HTML code for a login form. This form allows users to enter their username and password to log in to the system.
- Added HTML code for a signup form. This form allows new users to register by entering their details such as first name, last name, username, password, user type (buyer or seller), and address.
- Refactored the user authentication system. This includes improvements to the code structure and logic, making it more efficient and maintainable.
- Added a logout feature. This allows users to securely log out of the system.
Please review the changes and merge the pull request if everything is in order. If there are any issues or questions, feel free to leave comments.
=> Enhance User Authentication and Add Login/Signup Forms

app.js, controllers/userController.js, package-lock.json, package.json, routes/reviews.js, views/login_form.ejs
Changes include:
1. **Rate Limiter Middleware**: To protect our application from brute-force attacks, a rate limiting middleware has been added. This will limit the number of requests a client can make in a certain timeframe (commit d517f88).
2. **User Locals Middleware**: A middleware has been added to attach the user object to the response locals. This allows us to access the user object in our views and display personalized content (commit 86dd9c8).
3. **Login Functionality Bug Fix**: A bug in the login functionality has been fixed to ensure users can log in correctly (commit 12e4f31).
4. **Review Export Issue Fix**: An issue with exporting a review has been fixed (commit 7048dfe).
Please review these changes and merge them into the main branch if everything looks good.
=> Introduces several updates to improve the security and user experience

views/login_form.ejs, views/signup_form.ejs
This pull request focuses on enhancing the user experience by modifying fonts throughout the application. Consistent and carefully selected fonts contribute significantly to readability and overall aesthetics.
1. **Modify Fonts (Commit: 917c650)**
- Updated the font styles across the application for improved readability and a more cohesive visual appearance.
- Checked and adjusted font sizes, weights, and styles to ensure a consistent and pleasant user interface.
1. After merging this pull request, run the application and navigate through different views to observe the changes in font styles.
2. Verify that the modified fonts align with the design principles and maintain readability.
- Please review the font modifications and provide feedback.
- Ensure that the changes adhere to the …
=> Enhancement: Font Modification for Improved User Experience

controllers/bookController.js, models/author.js, models/book.js, seeds/seed.js
Changes include:
1. **Seller Field Added to Book Model**: The Book model has been updated to include a `seller` field. This field is a reference to the Seller model, allowing us to associate each book with a seller (commit ea1744d).
2. **Author Model Name Fix**: A fix has been made to the name of the Author model (commit d512141).
These changes improve the structure of our data and the relationships between our models. Please review and merge these changes into the main branch if everything looks good.
=> Update Book and Author Models

public/stylesheets/nav.css, public/stylesheets/templatemo-pod-talk.css, views/about.ejs, views/partials/navbar.ejs
This pull request introduces two key enhancements to improve the user experience on our platform.
- Implemented a visually appealing "Add to Cart" icon to streamline the shopping experience.
- The new icon provides users with a clear and intuitive way to add items to their shopping cart.
- Enhanced the navigation bar to ensure a more user-friendly and cohesive design.
- The updates to the navbar contribute to a consistent and aesthetically pleasing layout across the website.
- Commit fc9440c: Added the "Add to Cart" icon for improved shopping functionality.
- Commit ca635ac: Updated the "About Us" page for enhanced content and presentation.
This pull request aims to enhance the overall usability and visual appeal of our platform. Please review and provide feedback.
=> 🛒 Enhancements: Add to Cart Icon & Navbar Update & About us Update

public/stylesheets/log.css, views/login_form.ejs, views/signup_form.ejs
- Modified the styling of the login and sign-up buttons for better user experience.
- Updated the button appearance to improve visibility and alignment.
- Adjusted colors and sizes to maintain a consistent design across the application.
[Attach screenshots or describe visual changes if necessary.]
- [List any related issues or JIRA tickets that are addressed by this pull request, if applicable.]
- [Briefly describe the testing you performed to ensure the changes work as expected.]
- [Include any additional information that might be relevant to reviewers.]
=> Update Login and Sign-Up Buttons

public/stylesheets/log.css, views/signup_form.ejs
**Pull Request Description:**
This pull request addresses the changes made in commit `77339e1` on the `main` branch. The focus of this update is on the signup page, with improvements and modifications introduced to enhance user experience and functionality.
**Changes Made:**
- [Briefly list key changes, enhancements, or fixes made in the commit]
- [Include any relevant context or reasoning behind the changes]
**Testing:**
- [Describe the testing process undertaken to ensure the stability and correctness of the changes]
- [Include any test cases or scenarios covered]
**Screenshots:**
- [If applicable, attach before-and-after screenshots to visually represent the changes]
**Additional Notes:**
- [Any other relevant information, considerations, or points for review]
- [Mention if further …
=> Update signup page

public/stylesheets/profile.css, views/user_profile.ejs
- **Profile Refinement:** Implemented a comprehensive overhaul of the user profile interface, enhancing its visual appeal and overall user experience.
- **Additional Fields:** Expanded the user profile with new fields to capture more detailed and relevant information, providing a more comprehensive user profile.
- **Performance Optimization:** Conducted optimizations to improve the performance of the user profile module, ensuring swift loading and responsiveness.
**How to Test:**
1. Navigate to the user profile section.
2. Explore the new fields and features added for customization.
**Additional Notes:**
This enhancement aligns with our commitment to providing an exceptional user experience. Your feedback and reviews are highly appreciated.
Thank you for your attention and consideration. …
=> Enhancement: User Profile

app.js, controllers/authorController.js, controllers/categoryController.js, controllers/publisherController.js, models/category.js, routes/authors.js, routes/categories.js, routes/publishers.js, views/author_form.ejs, views/category_form.ejs, views/createBook.ejs, views/publisher_form.ejs
- Added a publisher router to `app.js`.
- Refactored select elements in `createBook.ejs`.
- Added a publisher form in the ejs template.
- Implemented publisher routes and controller.
- Added CRUD operations in the publisher controller.
- Added an author router to `app.js`.
- Added a button to create a new author in the `createBook` view.
- Added an author form in the ejs template.
- Implemented author routes and controller.
- Added CRUD operations in the author controller.
- Added a category form in the ejs template.
- Refactored `categoryController.js` to implement category list and create functionality.
- Refactored category routes.
- Added a button to add a new category in the `createBook` view.
- Added validation rules for category names.
- Made necessary adjustments and refactoring …
=> Implement Publishers, Authors, and Categories Management

public/stylesheets/log.css, public/stylesheets/nav.css, views/login_form.ejs, views/partials/navbar.ejs, views/signup_form.ejs
This pull request addresses multiple enhancements to the project, focusing on improving the login and signup pages while introducing a new Search button feature.
- **bf00aad:** Adjusted login and signup pages to improve user experience and visual aesthetics.
- **2894e4f:** Added a new Search button to enable users to quickly find relevant content.
The adjustments to the login and signup pages aim to streamline the user onboarding process and create a more intuitive interface. The addition of the Search button enhances user navigation and facilitates content discovery within the application.
1. Navigate to the login page and observe the updated layout and design changes.
2. Access the signup page to experience the improved user interface.
3. Locate and interact with the newly added Search …
=> Feature: Enhance Login and Signup Pages, Introduce Search Button

controllers/bookController.js, routes/books.js, views/bookSearchResult.ejs
This pull request adds the ability to search for books by title, author, publisher, and category. The following changes have been made:
- Added a new `search_book` function in `bookController.js` that handles the search functionality. This function uses the query parameters from the GET request to build a search query and returns the matching books.
- Updated the book routes to include a new `/search` route that uses the `search_book` function.
- Added a new `bookSearchResult` view that displays the search results.
- Refactored `bookController.js` for improved readability.
These changes allow users to search for books using different criteria, improving the usability of the application.
Commit 7f7a825: Added the `bookSearchResult` view.
Commit 8eee0bd: Updated the book routes to include …
=> Implement Book Search Functionality

controllers/bookController.js, views/partials/navbar.ejs
This pull request enhances the book search functionality and updates the navbar to include the search box. The following changes have been made:
- Updated the `search_book` function in `bookController.js` to use case-insensitive regular expressions for querying title, author, publisher, and category. This allows for more flexible searching and improves the user experience.
- Updated the navbar to include a search box. This allows users to search for books directly from the navbar, making the search functionality more accessible.
These changes improve the usability of the book search functionality and make it easier for users to find the books they are looking for.
Commit d227a48: Updated the search functionality in the navbar.
Commit 61469b8: Refactored the `search_book` function to use …
=> Enhance Book Search Functionality and Update Navbar

views/about.ejs, views/login_form.ejs, views/partials/navbar.ejs, views/signup_form.ejs
I'm really tired so I can't add a description but I know you know
=> Add some transitions

controllers/bookController.js, controllers/reviewController.js, controllers/userController.js, views/bookSearchResult.ejs, views/partials/navbar.ejs, views/signup_form.ejs
This pull request introduces several enhancements to improve the user experience:
- Added success and error alerts to the signup form to provide immediate feedback to the user during the signup process.
- Updated the search input placeholder to make it more descriptive and user-friendly.
- Added a "No results found" message to be displayed when a search yields no results, improving user feedback during search operations.
- Added flash messages for login error handling to provide immediate feedback to the user during the login process.
- Refactored the `createReview_post` function for improved readability and maintainability.
- Refactored the `search_book` function to handle empty queries, improving the robustness of the search functionality.
These changes improve the usability of the …
=> Enhance User Experience with Improved Alerts and Search Functionality

controllers/userController.js, views/update_user_profile.ejs, views/user_profile.ejs
This pull request introduces the ability for users to update their profile information. 
Changes include:
- Added an "Edit Profile" button on the user profile page (commit: 3682b91)
- Implemented the functionality to update user profile (commit: 02ac807)
- Created a new page for updating user profile (commit: 7c1e91b)
These changes allow users to easily update their profile information such as username, wallet amount, and address. The username and wallet amount fields are read-only to prevent unwanted changes.
Please review the changes and let me know if anything needs to be adjusted. Thank you.
=> Add Update User Profile Functionality

controllers/bookController.js, public/javascripts/bookInstance.js, public/stylesheets/bookInstance.css, views/bookInstance.ejs
=> Adjust Book instance

public/stylesheets/bookInstance.css, views/bookInstance.ejs
=> Design BookInstance

controllers/userController.js, views/update_user_profile.ejs
This pull request adds success and error alerts to the update_user_profile.ejs file and also adds a wallet_amount field to the user update functionality.
=> Add success and error alerts to update_user_profile.ejs and Add wallet_amount field to user update

controllers/userController.js, routes/users.js, views/user_profile.ejs
This pull request adds the Book and Review models and implements the deleteUser_post route. It also updates the user profile page with a new button for deleting the user profile.
=> Add Book and Review models, implement deleteUser_post

public/stylesheets/profile.css, views/update_user_profile.ejs, views/user_profile.ejs
I've just made the card of user profile be more realistic and I updated the edit profile file
=> Update user Profile

public/javascripts/bookInstance.js
This pull request fixes the rating functionality in the code. It addresses an issue where the rating was not being displayed correctly and adds the ability to hover over stars to see the rating before clicking.
=> Fix rating functionality

views/partials/cartPane.ejs
This pull request fixes a bug in the login functionality that was causing users to be unable to log in. The bug was caused by an incorrect validation check in the login form. This PR updates the validation logic to correctly handle all valid login inputs.
=> Fix bug in login functionality

public/stylesheets/books.css, views/books.ejs
=> Rework books page phase 1

controllers/userController.js, routes/users.js, views/change_password.ejs, views/user_profile.ejs
This pull request adds change password functionality to the user controller. It includes the necessary routes, controller methods, and views to allow users to change their password.
=> Add change password functionality to user controller

public/stylesheets/books.css, views/books.ejs, views/partials/navbar.ejs
Update the book overview and make it more beautiful
=> Book page Finished

controllers/userController.js, views/signup_form.ejs, views/user_profile.ejs
This pull request includes several code refactorings that aim to improve the performance of the application. The changes include optimizing algorithms, reducing unnecessary computations, and improving data structures. These improvements will result in faster execution times and a more efficient use of system resources.
=> Refactor code to improve performance

controllers/cartController.js, views/about.ejs, views/index.ejs, views/mybooks.ejs, views/updateBook.ejs, views/updateReview.ejs, views/user_profile.ejs
This pull request adds flash messages for successful and error operations in the cart views.
=> Add flash messages for cart operations

controllers/userController.js, views/update_user_profile.ejs, views/user_profile.ejs
In this pull request, I changed the user Profile to be the same before deleting the address attribute
=> Restore User profile

controllers/authorController.js, routes/authors.js
This pull request adds a new route and controller method for handling the GET request to create an author.
=> Add createAuthor_get route and controller method

views/createBook.ejs
This pull request updates the select element in the code to allow for multiple categories to be selected. This change is necessary to accommodate the requirements of the project.
=> Update select element to allow multiple categories

views/partials/cartPane.ejs, views/update_user_profile.ejs
There was a small issue in update user profile and I solve it <3
=> Fix update user profile issue

public/stylesheets/books.css, public/stylesheets/index.css, views/bookSearchResult.ejs, views/books.ejs, views/mybooks.ejs
1) I made search result and my books page to be just like Books page
2) I fixed the home issue for the phone users
=> Fix home issue and Update my books and search result 

public/stylesheets/bookInstance.css, public/stylesheets/books.css, views/bookInstance.ejs, views/bookSearchResult.ejs, views/mybooks.ejs
There was some issues in the last commit and I should have fixed it
=> Fix some issues in books and bookInstance pages

public/stylesheets/bookInstance.css
=> Add scroll bar for bookInstance

controllers/bookController.js, views/bookInstance.ejs, views/books.ejs
This pull request refactors the cart and order handling in the bookController.js and bookInstance.ejs files. It updates the code to use the Cart and Order models, and makes changes to the getAllBooks, getBookById, and viewBook_get functions.
=> Refactor cart and order handling in bookController.js and bookInstance.ejs

views/bookInstance.ejs
This pull request refactors the bookInstance.ejs view file to improve code readability and maintainability.
=> Refactor bookInstance.ejs view

views/book_instance.ejs, views/books.ejs
This pull request refactors the conditional statement for adding books to the cart. The changes ensure that the statement correctly checks if a book is already in the cart or has been bought by the user before allowing it to be added to the cart.
=> Refactor conditional statement for adding books to cart

controllers/userController.js, models/user.js
This pull request adds password length validation to the signup form. Users will now be required to enter a password that is at least 4 characters long.
=> Add password length validation to signup form

views/book_search_result.ejs, views/checkout.ejs, views/mybooks.ejs
In this pull request I added some icons I forgot to add after deletion bootstrap files
=> Add some missing Designs

controllers/orderController.js, package-lock.json, package.json, views/checkout.ejs
=> Revert "Install stripe and add payment method with stripe"

controllers/orderController.js
This pull request refactors the orderController.js file to improve code readability and maintainability. The changes include formatting, variable naming, and code organization.
=> Refactor orderController.js for readability and maintainability

controllers/orderController.js
=> Revert "Refactor orderController.js for readability and maintainability"
